### ISSUE TITLE
Create features

### ISSUE THREAD

**Issue by jayvdb** [kstasik/schema-tools#71]
After https://github.com/kstasik/schema-tools/pull/69 is accepted, it would be helpful to split the dependencies and library into cargo features, so that lib users (and even binary builders) can choose which features they need, if they want less dependencies and faster build times.

I'm happy to do an initial cut of this, as there are a few large dependencies I would like to avoid.

**Comment by kstasik** [comment]
Can you please explain how do you want use this library? Maybe send an example of build.rs? Generally speaking most common scenario was to generate multiple http clients using openapi specification and create server definition like this: https://github.com/kstasik/schema-tools#example-of-usage

**Comment by jayvdb** [comment]
Sure. At the moment we're only using the `resolve` subsystem. We'd like to use the `codegen` subsystem, but the templates have a few problems compared to https://github.com/oxidecomputer/progenitor which we're using for codegen. I've got a task to describe those problem, but it isnt on the critical path because progenitor is good enough.  But https://github.com/oxidecomputer/progenitor/issues/228 means it doesnt do the resolve stage, so we need schematools + progenitor.
