### ISSUE TITLE
Cargo.toml package.version not incrementing

### ISSUE THREAD

**Issue by jayvdb** [kstasik/schema-tools#72]
The version of the GitHub tags is incrementing, currently at [0.7.1](https://github.com/kstasik/schema-tools/releases/tag/v0.7.1), while the Cargo.toml package.version is still 0.6.0

**Comment by kstasik** [comment]
Issue has been fixed. [python commitzen](https://commitizen-tools.github.io/commitizen/) doesn't use regular expressions - it just replaces old version with new one (version in the file was outdated).
