### ISSUE TITLE
feat: publish cli on crates.io

### ISSUE THREAD

**Issue by clbarnes** [kstasik/schema-tools#88]
`cargo install schematools` doesn't find a binary crate. `cargo add schematools` doesn't seem to install the CLI.

**Comment by jayvdb** [comment]
The cli is called `schematools-cli` , c.f. https://github.com/kstasik/schema-tools/blob/master/crates/cli/Cargo.toml

However @kstasik is only publishing the library to crates.io, not the CLI. c.f. https://github.com/kstasik/schema-tools/pull/77#discussion_r1125090300

**Comment by kstasik** [comment]
This application is used for languages like rust, typescript, golang (contract first approach in case of REST apis). That is why it's published as a binary on github releases. Example of usage:

https://github.com/kstasik/schema-tools-templates/blob/master/tests/rust-axum/Makefile#L32-L44

But if you have a need to install it using `cargo` MR is welcomed.

**Comment by jayvdb** [comment]
It would be great if it could be published.  I currently have an entry like the following in my Makefile.toml

```toml
[tasks.resolve-yaml]
workspace = false
install_crate = { crate_name = "schematools", binary = "schematools-cli", test_arg = "--help" }
install_crate_args = ["--git", "https://github.com/kstasik/schema-tools/"]
command = "schematools-cli"
args = [
  "process",
  "dereference",
  "--create-internal-references",
  "--output",
  "yaml",
  "--to-file",
  "openapi/resolved.yaml",
  "openapi/input.yaml",
] 
```

this is slow, because it uses git, and unstable because it uses git without a rev name because I do want updates.

I'll create a PR

**Comment by jayvdb** [comment]
https://crates.io/crates/schematools-cli

done in https://github.com/kstasik/schema-tools/pull/104
