### ISSUE TITLE
Update json-patch

### ISSUE THREAD

**Issue by jayvdb** [kstasik/schema-tools#93]
json-patch is now 1.0 . Version 0.3 had some breaking changes which make this non-trivial to update, but it doesnt look too difficult.  from their CHANGELOG

> - Removed `json_patch::from_value`. Use `serde_json::from_value` instead.

**Comment by kudlatyamroth** [comment]
fixed in [0.16](https://github.com/kstasik/schema-tools/commits/v0.16.0)
