### ISSUE TITLE
Docker image for cli crate?

### ISSUE THREAD

**Issue by dinosath** [kstasik/schema-tools#96]
Hello I created a dockerfile and workflow for building a docker image based schematools-cli crate. Does anyone else think its useful? If so i could create a pull request for that.

P.S. I created a ticket since discussions are not enabled and i am not sure where i should have posted this question

**Comment by kstasik** [comment]
If you need a docker image on a docker hub that is fine with me - it's definitely a good feature. In our case we are using binaries directly, like this:

https://github.com/kstasik/schema-tools-templates/blob/master/tests/rust-axum/Makefile#L37
